apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  labels:
    app: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: 905418202149.dkr.ecr.us-east-1.amazonaws.com/orders-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80  # change if your Node app uses a different port
---
apiVersion: v1
kind: Service
metadata:
  name: orders
  labels:
    app: orders
spec:
  type: ClusterIP
  selector:
    app: orders
  ports:
  - port: 80        # service port inside the cluster
    targetPort: 80  # must match the containerPort above
